name: test-x86_64-windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        target: [x86_64-windows-gnu, x86_64-windows]
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.os }}, ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run Tests
        run: zig build test -Dtarget=${{ matrix.target }}
